version: '3.3'

services:
  db:
    image: mysql:8.0.21
    restart: always
    environment:
      - MYSQL_DATABASE=my-db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "${DB_PORT}:${DB_PORT}"
    expose:
      # Opens port 3306 on the container
      - "${DB_PORT}"
    # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  # Names our volume
  volumes:
    my-db: